apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: garnet
  name: garnet
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: garnet
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chart-default: "true"
        io.kompose.service: garnet
    spec:
      containers:
        - image: ghcr.io/microsoft/garnet
          name: garnet
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: garnetdata
      restartPolicy: Always
      volumes:
        - name: garnetdata
          persistentVolumeClaim:
            claimName: garnetdata
