apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: garnetdata
  name: garnetdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
